name: Build and upload image
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  pi-gen-upload-image:
    runs-on: ubuntu-latest
    steps:
      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          image-name: test
          # List of stage name to execute in given order. Relative and absolute paths to 
          # custom stage directories are allowed here. Note that by default pi-gen exports 
          # images in stage2 (lite), stage4 and stage5. You probably want to hook in custom 
          # stages before one of the exported stages. Otherwise, the action will make sure 
          # any custom stage will include an image export directive.
          stage-list: stage0 stage1 stage2 stage3 stage4 ./stage4a
          export-last-stage-only: true

      - name: Delete existing release and tag
        if: success()
        id: create-and-upload-release
        run: |
          git push --delete origin continuous || true # Delete existing release and tag

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.build.outputs.image-path }}
          tag_name: continuous
          target_commitish: ${{ github.sha }}
          draft: false
