name: Build and upload image
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  pi-gen-upload-image:
    runs-on: ubuntu-latest
    steps:
      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          image-name: test
          # List of stage name to execute in given order. Relative and absolute paths to 
          # custom stage directories are allowed here. Note that by default pi-gen exports 
          # images in stage2 (lite), stage4 and stage5. You probably want to hook in custom 
          # stages before one of the exported stages. Otherwise, the action will make sure 
          # any custom stage will include an image export directive.
          stage-list: stage0 stage1 stage2 stage3 stage4

      - name: Check if release "continuous" exists and delete it, then create and upload release
        if: success()
        id: create-and-upload-release
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt-get update
          sudo apt-get install -y gh jq
          release_id=$(gh release view continuous --json id --repo "${{ github.repository }}" | jq -r '.id // empty')
          if [ -n "$release_id" ]; then
            gh release delete "$release_id" --repo "${{ github.repository }}" -y
          fi

          release_id=$(gh release create continuous --title "continuous" --repo "${{ github.repository }}" --json id | jq -r '.id // empty')
          if [ -n "$release_id" ]; then
            gh release upload "$release_id" "${{ steps.build.outputs.image-path }}" --repo "${{ github.repository }}" --clobber
            echo "::set-output name=release_id::$release_id"
          fi
